basePath: /api/v1
definitions:
  interfaces.Response:
    properties:
      code:
        description: 状态, [200=成功, 400=失败, 401=未登录, 403=无相关权限, 404=请求接口不存在, 405=请求方法不允许,
          500=系统错误]
        type: integer
      data:
        description: 数据
      msg:
        description: 信息
        type: string
    type: object
  interfaces.UserLoginReq:
    properties:
      password:
        description: 密码
        type: string
      username:
        description: 用户名
        type: string
    type: object
  interfaces.UserRegReq:
    properties:
      email:
        description: 邮箱
        type: string
      password:
        description: 密码
        type: string
      source:
        description: 来源
        type: string
    type: object
host: http://localhost
info:
  contact: {}
  description: hios是一款轻量级的开源在线项目文件管理工具，提供各类文档协作工具。
  license:
    name: AGPL-3.0 license
    url: http://www.gnu.org/licenses/
  termsOfService: https://www.gnu.org/
  title: hios
  version: "1.0"
paths:
  /api/v1/login:
    post:
      consumes:
      - application/json
      description: 登录
      parameters:
      - description: request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/interfaces.UserLoginReq'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/interfaces.Response'
      summary: 登录
      tags:
      - System
  /api/v1/register:
    post:
      consumes:
      - application/json
      description: 注册
      parameters:
      - description: request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/interfaces.UserRegReq'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/interfaces.Response'
      summary: 注册
      tags:
      - System
swagger: "2.0"
